name: devops-Scheduled

on:
  schedule:
    - cron: "45 19 * * 1"
    - cron: "0 0 * * 1"
    - cron: "0 3 * * 1"
    - cron: "25 2 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git
        uses: actions/checkout@v4

      - name: Pruebas React
        run: |
          echo "Corriendo pruebas React..."
          echo "Pruebas completas"

  build:
    runs-on: ubuntu-20.04
    needs: [test]

    steps:
      - name: Checkout git
        uses: actions/checkout@v4

      - name: Dependencias y building
        run: |
          npm install
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout git
        uses: actions/checkout@v4

      - name: Deploy a produccion
        run: |
          echo "Deploying..."
          echo "Deploy completo!"
